# Generated by Django 5.1.1 on 2025-02-12 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountdownTimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('end_time', models.DateTimeField()),
            ],
        ),
    ]
